# Generated by Django 5.0.1 on 2026-02-27 12:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorprofile',
            name='offers_intro_call',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mentorsession',
            name='cancellation_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mentorsession',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mentorsession',
            name='cancelled_by',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='mentorsession',
            name='mentor_replied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mentorsession',
            name='mentor_reply',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mentorsession',
            name='refund_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.CreateModel(
            name='MentorUnavailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unavailability', to='mentorship.mentorprofile')),
            ],
            options={
                'verbose_name_plural': 'Mentor Unavailability',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='UserBundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessions_remaining', models.IntegerField()),
                ('stripe_checkout_session', models.CharField(blank=True, max_length=200)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('bundle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='mentorship.mentorbundle')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sold_bundles', to='mentorship.mentorprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-purchased_at'],
            },
        ),
        migrations.CreateModel(
            name='MentorStudentNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_notes', to='mentorship.mentorprofile')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('mentor', 'student')},
            },
        ),
    ]
