# Generated by Django 5.0.1 on 2024-06-16 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_jobs_delete_practice'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='company',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='jobs',
            name='job_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='jobs',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='jobs',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
