# Generated by Django 5.0.1 on 2024-06-18 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_jobs_company_jobs_job_type_jobs_location_jobs_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='job_rate',
            field=models.IntegerField(blank=True, default=10),
            preserve_default=False,
        ),
    ]
