# Generated by Django 5.0.1 on 2026-02-19 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_jobs_job_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='job_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
