# Generated by Django 5.0.1 on 2026-03-15 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_notification_prefs_profile_privacy_prefs'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='daily_minutes',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='profile',
            name='goal',
            field=models.CharField(blank=True, choices=[('speaking', 'Speaking in conversations'), ('writing', 'Writing emails and documents'), ('exam', 'Preparing for IELTS / TOEFL / PTE'), ('interview', 'Job interviews in English')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='level',
            field=models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='onboarding_complete',
            field=models.BooleanField(default=False),
        ),
    ]
